# application.yml
spring:
  datasource:
    url: jdbc:mariadb://43.201.154.250:3306/RMsoft
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml